aop:
  include_paths:
    - /Users/lidanyang/project/esd-projects/esd-core/exampleClass/src
scan:
  include_paths:
    examples: /Users/lidanyang/project/esd-projects/esd-core/exampleClass/src

mysql:
  default:
    host: '127.0.0.1'
    username: 'root'
    password: '123456'
    db: 'oreiex'
    prefix: "t_"

redis:
  default:
    host: '127.0.0.1'